include:
  - project: 'homeserve/udp/templates'
    file: '/.deployer.yml'
    ref: 'master'

stages:
  - build
  - image
  - deploy
  - deleteOps

variables:
  DOCKER_HOST: "tcp://0.0.0.0:2375"
  VAULT_TOKEN: "s.8v693qlomb22gLwI9eSp7CFy"

build:
  stage: build
  image: golang
  script:
    - GOOS=linux go build -o ./app .
  artifacts:
    paths:
      - ./app
    expire_in: 2 days

deploy_debug:
  extends: .deploy_prod

deploy_staging:
  extends: .deploy_staging

build_image:
  extends: .build_image

stop_review_app:
  extends: .stop_review_app