include:
  - project: 'homeserve/udp/templates'
    file: '/.deployer.yml'
    ref: 'master'

stages:
  - build
  - image
  - deploy

build:
  stage: build
  image: golang
  script:
    - GOOS=linux go build -o ./app .
  artifacts:
    paths:
      - ./app
    expire_in: 1 days

deploy_debug:
  extends: .deploy_prod

build_image:
  extends: .build_image